### ISSUE TITLE
[ansi_color] Remove all the arc<mutex<_>> & replace w/ unsafe

### ISSUE THREAD

**Issue by nazmulidris** [r3bl-org/r3bl_rs_utils#126]
Context:
- Repo: https://github.com/r3bl-org/r3bl_rs_utils/tree/main/ansi_color
- Crate: https://crates.io/crates/r3bl_ansi_color

Related to https://github.com/r3bl-org/r3bl_rs_utils/issues/108

The reason for adding Arc<Mutex<_>> (and replace unsafe like is used here https://github.com/r3bl-org/r3bl_rs_utils/blob/main/tui/src/tui/terminal_window/static_global_data.rs#L173) was to remove test flakiness. And it didn't really address that problem at all.

Change detect colors support & set override so they use `unsafe` just like `r3bl_tui` does to be consistent.

FYI - Currently `serial_test = "2.0.0"` is used to remove flakiness from tests.

**Comment by LuciAkirami** [comment]
Hey @nazmulidris , can I take up this issue?

**Comment by nazmulidris** [comment]
@LuciAkirami Thank you 🙏🏽 This issue is all yours. Please let me know if you have any questions.
