### ISSUE TITLE
[ansi_color] Add comprehensive tests for SGR codes

### ISSUE THREAD

**Issue by nazmulidris** [r3bl-org/r3bl_rs_utils#127]
The `tests` module in the following file:
<https://github.com/r3bl-org/r3bl_ansi_color/blob/main/src/ansi_escape_codes.rs#L83>
needs a lot more tests that check all the variants of the `SgrCode` enum.

Currently the following variants are not tested:
1. Dim
2. Italic
3. Underline
4. SlowBlink
5. RapidBlink
6. Invert
7. Hidden
8. Strikethrough
9. Overline

If you have [github copilot](https://github.com/features/copilot) it can actually generate these test cases for you 😄

**Comment by LuciAkirami** [comment]
Hey @nazmulidris , can I work on this issue?

**Comment by nazmulidris** [comment]
@LuciAkirami  That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
