### ISSUE TITLE
[tuify] Use nice ANSI symbols instead of ">" to decorate what row is currently selected

### ISSUE THREAD

**Issue by nazmulidris** [r3bl-org/r3bl_rs_utils#133]
Context:
- Crate: https://crates.io/crates/r3bl_tuify
- Repo: https://github.com/r3bl-org/r3bl_rs_utils/tree/main/tuify

We can do a lot more to decorate the selection with nice glyphs, instead of just ">" prefix. So it looks more like a real app. Here's an example of glyphs we can use. 

https://github.com/r3bl-org/r3bl-ts-utils/blob/8751aadef6a110ae409e5c5a0ecfc263a95b2741/src/tui-figures/symbols.ts#L217

It is possible to use radio buttons, check boxes, emoji, and even drawing rounded corners and boxes using these ANSI symbols.

**Comment by nisargparikh69** [comment]
@nazmulidris Can you please give me appropriate rights so that I can add PR for this? I have change ready on my local for this issue

**Comment by nisargparikh69** [comment]
@nazmulidris I have raised PR please review
