### ISSUE TITLE
[core] Why is there a dependency on `reqwest` crate here?

### ISSUE THREAD

**Issue by nazmulidris** [r3bl-org/r3bl_rs_utils#140]
Currently the [`r3bl_rs_utils_core`](https://crates.io/crates/r3bl_rs_utils_core) crate (in the [`core`](https://github.com/r3bl-org/r3bl_rs_utils/tree/main/core) folder) has a dependency on `reqwest`

It was discovered during this audit:
![image](https://github.com/r3bl-org/r3bl_rs_utils/assets/2966499/e3bf1170-2818-4959-88f0-962817fc15c1)from https://github.com/r3bl-org/r3bl_rs_utils/issues/112

The license terms are good, however, the question arises why is it marked as a dependency in the first place? If there is a legit reason then we can retain the dependency and leave this as-is, otherwise we can drop the dependency.

**Comment by Harshil-Jani** [comment]
@nazmulidris I investigated on this. I found that https://github.com/r3bl-org/r3bl_rs_utils/blob/68c0fe7967db6e84d36ad45e48bd9495ebdb6cb3/core/src/decl_macros.rs#L233 there exist a macro `make_api_call_for` which uses reqwest. But the macro is not used anywhere so I feel this safe to be removed from everywhere and remove the reqwest crate if we are not using it anywhere else.

**Comment by nazmulidris** [comment]
@Harshil-Jani It is safe to remove this macro. It was being used in another repo (shown below).

https://github.com/r3bl-org/address-book-with-redux-tui/blob/main/src/json_rpc/mod.rs#L22
