### ISSUE TITLE
How do I mutate the value inside a node?

### ISSUE THREAD

**Issue by freddycansic** [r3bl-org/r3bl_rs_utils#99]
Looked through the docs and couldn't quite find this. Is it possible? Thanks

**Comment by nazmulidris** [comment]
If you take a look at this test https://github.com/r3bl-org/r3bl_rs_utils/blob/51000bf539f317a0f685ab279891c4a6c7d1d045/tests/test_tree_memory_arena.rs#L41 imagine adding the following block to it:
```rust
    {
        let node_1_id = 0_usize;
        let node_1_ref = dbg!(arena.get_node_arc(node_1_id).unwrap());
        node_1_ref.write().unwrap().payload = 100;
    }
```

A `NodeRef` is just `pub type NodeRef<T> = Arc<RwLock<Node<T>>>;`. So you can just use `Arc` and `RWLock` (https://doc.rust-lang.org/std/sync/struct.RwLock.html) to mutate it.

**Comment by nazmulidris** [comment]
Also I just added this example to the test (this is in a branch so it won't show up to `main` until that has been merged in the future).
```rust
    // Mutate node_1.
    {
        let node_1_id = 0_usize;
        {
            let node_1_ref = dbg!(arena.get_node_arc(node_1_id).unwrap());
            node_1_ref.write().unwrap().payload = 100;
        }
        assert_eq2!(
            arena.get_node_arc(node_1_id).unwrap().read().unwrap().payload,
            100
        );
    }
```

**Comment by freddycansic** [comment]
Thanks a lot. Would you consider updating [this link](https://github.com/r3bl-org/r3bl_rs_utils/blob/main/tests/tree_memory_arena_test.rs) in [this README section](https://github.com/r3bl-org/r3bl_rs_utils#tree_memory_arena-non-binary-tree-data-structure) to [the working version](https://github.com/r3bl-org/r3bl_rs_utils/blob/main/tests/test_tree_memory_arena.rs)?

**Comment by nazmulidris** [comment]
You're most welcome. And that is a good idea. I will update the README.md w/ your suggestion as well 👍🏽. All of this will land in the `main` branch when I merge the current feature branch onto it.

**Comment by nazmulidris** [comment]
Here's the new snippet I am adding to README.md:

Here's how you get weak and strong references from the arena (tree), and tree walk:

```rust
use r3bl_rs_utils::{
  tree_memory_arena::{Arena, HasId, MTArena, ResultUidList},
  utils::{style_primary, style_prompt},
};

let mut arena = Arena::<usize>::new();
let node_1_value = 42 as usize;
let node_1_id = arena.add_new_node(node_1_value, None);

// Access node.
{
  assert!(arena.get_node_arc(&node_1_id).is_some());
  let node_1_ref = dbg!(arena.get_node_arc(&node_1_id).unwrap());
  let node_1_ref_weak = arena.get_node_arc_weak(&node_1_id).unwrap();
  assert_eq!(node_1_ref.read().unwrap().payload, node_1_value);
  assert_eq!(
    node_1_ref_weak.upgrade().unwrap().read().unwrap().payload,
    42
  );
}

// Node does not exist.
{
  let node_id_dne = 200 as usize;
  assert!(arena.get_node_arc(&node_id_dne).is_none());
}

// Walk tree.
{
  let node_1_id = 0 as usize;
  let node_list = dbg!(arena.tree_walk_dfs(&node_1_id).unwrap());
  assert_eq!(node_list.len(), 1);
  assert_eq!(node_list, vec![0]);
}

// Mutate node.
{
  let node_1_id = 0_usize;
  {
    let node_1_ref = dbg!(arena.get_node_arc(node_1_id).unwrap());
    node_1_ref.write().unwrap().payload = 100;
  }
  assert_eq2!(
    arena.get_node_arc(node_1_id).unwrap().read().unwrap().payload,
    100
  );
}
```

**Comment by freddycansic** [comment]
May I also ask why `Arena<T>` is not `Clone`?

**Comment by nazmulidris** [comment]
The type over which `Arena` is generic is the one that can be cloned: `T: Debug + Clone + Send + Sync`.

Since the contents of the `Arena` support interior mutability and can reference other contents inside it, cloning it seemed unnecessary.

You could just implement `Clone` yourself for `Arena` if you like. It is simply a struct holding a hash map & counter.
